const CREATE_PRODUCT_REQUESTED = 'CREATE_PRODUCT_REQUESTED'
const CREATE_PRODUCT_SUCCEEDED = 'CREATE_PRODUCT_SUCCEEDED'
const CREATE_PRODUCT_FAILED = 'CREATE_PRODUCT_FAILED'

export { CREATE_PRODUCT_REQUESTED, CREATE_PRODUCT_SUCCEEDED, CREATE_PRODUCT_FAILED }
