const CREATE_PRODUCT_REQUESTED = 'CREATE_PRODUCT_REQUESTED'
const CREATE_PRODUCT_SUCCEEDED = 'CREATE_PRODUCT_SUCCEEDED'
const CREATE_PRODUCT_FAILED = 'CREATE_PRODUCT_FAILED'
const CATEGORIES_REQUESTED = 'CATEGORIES_REQUESTED'
const CATEGORIES_SUCCEEDED = 'CATEGORIES_SUCCEEDED'
const CATEGORIES_FAILED = 'CATEGORIES_FAILED'
const GET_PRODUCTS_REQUESTED = 'GET_PRODUCTS_REQUESTED'
const GET_PRODUCTS_SUCCEEDED = 'GET_PRODUCTS_SUCCEEDED'
const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED'

export {
    CREATE_PRODUCT_REQUESTED,
    CREATE_PRODUCT_SUCCEEDED,
    CREATE_PRODUCT_FAILED,
    CATEGORIES_REQUESTED,
    CATEGORIES_SUCCEEDED,
    CATEGORIES_FAILED,
    GET_PRODUCTS_REQUESTED,
    GET_PRODUCTS_SUCCEEDED,
    GET_PRODUCTS_FAILED,
}
